spring:
  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  datasource:
    url: jdbc:h2:mem:mini-blog-db
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
  data:
    rest:
      base-path: api
  flyway:
    user: sa
    url: jdbc:h2:mem:mini-blog-db
    enabled: false
  jackson:
    time-zone: UTC

app:
  jwt:
    secret: JWTSuperSecretKey
    expiration-in-ms: 604800000
